### ISSUE TITLE
Support for NumPy > 2.0.0

### ISSUE THREAD

**Issue by lochhh** [talmolab/sleap-io#114]
In PR #107 NumPy was constrained to `<2.0.0` in [env.yml](https://github.com/talmolab/sleap-io/blob/2bc3d5210c46bdb25413d25970c4bdc7adb6e8cc/environment.yml#L17) but not in [pyproject.toml](https://github.com/talmolab/sleap-io/blob/2bc3d5210c46bdb25413d25970c4bdc7adb6e8cc/pyproject.toml#L23), so when sleap-io is installed via pip, the latest NumPy is installed. 

This led to the following errors and deprecation warnings (in the tests):
- AttributeError: `np.string_` was removed in the NumPy 2.0 release. Use `np.bytes_` instead.
- sleap-io\sleap_io\io\video.py:151: DeprecationWarning: __array_wrap__ must accept context and return_scalar arguments (positionally) in the future. (Deprecated NumPy 2.0)
    is_grayscale = bool(np.all(test_img[..., 0] == test_img[..., -1]))

**Comment by talmo** [comment]
Thanks @lochhh!

Merged and available in [v0.1.8](https://github.com/talmolab/sleap-io/releases/tag/v0.1.8). Up on PyPI and will be up soon on conda-forge.
