### ISSUE TITLE
Error with `make_training_splits` method

### ISSUE THREAD

**Issue by gitttt-1234** [talmolab/sleap-io#117]
When running`labels.make_training_splits()` with `sleap-io v'0.1.8'`, the generated splits seems to be inconsistent as below: 
```
Source file: Labels(labeled_frames=1200, videos=1, skeletons=1, tracks=0, suggestions=0)

Splits: (Labels(labeled_frames=960, videos=1, skeletons=1, tracks=0, suggestions=0),
 Labels(labeled_frames=1, videos=1, skeletons=1, tracks=0, suggestions=0),
 Labels(labeled_frames=120, videos=1, skeletons=1, tracks=0, suggestions=0))

```

Notebook to recreate the error: https://colab.research.google.com/drive/1wnbrV8Yz6dakGV0ASqMoV94Pnvlg9LSL?usp=sharing

(Also for the sleap file in `Y:\\talmo\\foundation-datasets\\mice\\sleap-mice_of\\labels.full.v043.pkg.slp`)

Thanks!

**Comment by talmo** [comment]
This is now fixed in [v0.1.9](https://github.com/talmolab/sleap-io/releases/tag/v0.1.9).
